config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "friends" => "pages#friends"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
     
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Friends", friends_path %></li>
        <li><%= link_to "About us", about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-ends -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
	<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div class= "jumbotron center">
	<h1>About</h1>
	<p>Olcay Sarmaz Pinteresting App About</p>
	<p> <%= link_to "Learn More", root_path, class:"btn btn-primary btn-lg" %>
</div>

app/views/pages/friends.html.erb
<div class= "jumbotron center">
	<h1>Friends</h1>
	<p>This is going to be a list of your friends.</p>
</div>

app/views/pages/home.html.erb
<div class= "jumbotron center">
	<h1>Welcome to my Pinteresting! </h1>
	<p><a href="http://facebook.com/olcaysarmaz">Olcay Sarmaz</a> Pinteresting App</p>
	<%= link_to "Log in", "about", class: "btn btn-default btn-lg"%>
	 <%= link_to "Sign up", "about", class: "btn btn-primary btn-lg"%>
</div>